# Generated by Django 5.1.4 on 2026-02-21 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='programs.asset')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_completions', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'asset_completions',
                'indexes': [models.Index(fields=['user', 'program'], name='asset_compl_user_id_1f2e58_idx')],
                'unique_together': {('user', 'asset')},
            },
        ),
        migrations.CreateModel(
            name='ConsigneAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consigne_acceptances', to='programs.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consigne_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consigne_acceptances',
                'unique_together': {('user', 'step')},
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('responses', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='programs.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_submissions',
                'indexes': [models.Index(fields=['user', 'asset'], name='form_submis_user_id_32666e_idx'), models.Index(fields=['asset'], name='form_submis_asset_i_65d900_idx')],
            },
        ),
        migrations.CreateModel(
            name='QCMAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('passed', models.BooleanField()),
                ('answers', models.JSONField()),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_attempts', to='programs.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qcm_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qcm_attempts',
                'indexes': [models.Index(fields=['user', 'asset'], name='qcm_attempt_user_id_ca4517_idx')],
            },
        ),
        migrations.CreateModel(
            name='StepProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='locked', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='programs.program')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='programs.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'step_progress',
                'indexes': [models.Index(fields=['user', 'program'], name='step_progre_user_id_e2ac9b_idx')],
                'unique_together': {('user', 'step')},
            },
        ),
    ]
