# Generated by Django 5.1.4 on 2026-03-02 12:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_prisedecontact_prisedecontactasset'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseDeContactAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('prise_de_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='programs.prisedecontact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdc_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progress_prisedecontactacceptance',
                'unique_together': {('user', 'prise_de_contact')},
            },
        ),
    ]
