# Generated by Django 5.1.4 on 2026-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_prisedecontactacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepprogress',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
