# Generated by Django 5.1.4 on 2026-02-21 18:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('like_count', models.IntegerField(default=0)),
                ('heart_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testimonies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonyComment',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_comments', to=settings.AUTH_USER_MODEL)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testimonies.testimony')),
            ],
            options={
                'db_table': 'testimony_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonyReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='testimonies.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'testimony_reactions',
            },
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['author'], name='testimonies_author__930767_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['-created_at'], name='testimonies_created_0f9dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='testimony',
            index=models.Index(fields=['-like_count'], name='testimonies_like_co_52ccb0_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonycomment',
            index=models.Index(fields=['testimony'], name='testimony_c_testimo_d06a74_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonycomment',
            index=models.Index(fields=['author'], name='testimony_c_author__8aadea_idx'),
        ),
        migrations.AddIndex(
            model_name='testimonyreaction',
            index=models.Index(fields=['testimony'], name='testimony_r_testimo_b296bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testimonyreaction',
            unique_together={('testimony', 'user', 'reaction_type')},
        ),
    ]
