# Generated by Django 5.1.4 on 2026-03-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='video_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
