# Generated by Django 5.1.4 on 2026-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonies', '0002_testimony_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
