# Generated by Django 5.1.4 on 2026-02-21 18:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('qcm', 'QCM'), ('form', 'Form'), ('consigne', 'Consigne')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('passing_score', models.IntegerField(default=70)),
                ('consigne_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assets',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.TextField()),
                ('price', models.IntegerField()),
                ('duration_weeks', models.IntegerField()),
                ('presentation_video_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'programs',
                'indexes': [models.Index(fields=['is_active'], name='programs_is_acti_0a53dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='programs.program')),
            ],
            options={
                'db_table': 'degrees',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QCMQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('order_index', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='programs.asset')),
            ],
            options={
                'db_table': 'qcm_questions',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='programs.degree')),
            ],
            options={
                'db_table': 'steps',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='programs.step'),
        ),
        migrations.CreateModel(
            name='FormFieldDef',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('select_options', models.JSONField(blank=True, null=True)),
                ('order_index', models.IntegerField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='programs.asset')),
            ],
            options={
                'db_table': 'form_fields',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['asset'], name='form_fields_asset_i_10fbaf_idx')],
                'unique_together': {('asset', 'order_index')},
            },
        ),
        migrations.AddIndex(
            model_name='degree',
            index=models.Index(fields=['program'], name='degrees_program_2c737c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('program', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='qcmquestion',
            index=models.Index(fields=['asset'], name='qcm_questio_asset_i_bad082_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='qcmquestion',
            unique_together={('asset', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='step',
            index=models.Index(fields=['degree'], name='steps_degree__e33bb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together={('degree', 'order_index')},
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['step'], name='assets_step_id_de65cc_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['type'], name='assets_type_7f4a89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('step', 'order_index')},
        ),
    ]
