# Generated by Django 5.1.4 on 2026-03-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DegreeFile',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='programs.degree')),
            ],
            options={
                'db_table': 'degree_files',
                'ordering': ['order_index'],
                'indexes': [models.Index(fields=['degree'], name='degree_file_degree__fb0bd7_idx')],
                'unique_together': {('degree', 'order_index')},
            },
        ),
    ]
