# Generated by Django 5.1.4 on 2026-03-02 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_degreefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriseDeContact',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prises_de_contact', to='programs.degree')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prises_de_contact', to='programs.program')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prises_de_contact', to='programs.step')),
            ],
            options={
                'db_table': 'programs_prisedecontact',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='PriseDeContactAsset',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('external_url', models.TextField()),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prise_de_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='programs.prisedecontact')),
            ],
            options={
                'db_table': 'programs_prisedecontactasset',
                'ordering': ['order_index'],
            },
        ),
    ]
