# Generated by Django 5.1.4 on 2026-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_prisedecontact_prisedecontactasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('qcm', 'QCM'), ('form', 'Form'), ('consigne', 'Consigne'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='degreefile',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio'), ('video', 'Video'), ('image', 'Image')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prisedecontactasset',
            name='type',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('image', 'Image')], max_length=10),
        ),
    ]
