# Generated by Django 5.1.4 on 2026-02-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveReplaySession',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('external_url', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('is_live', models.BooleanField()),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_replay_sessions',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['is_live'], name='live_replay_is_live_978d6a_idx'), models.Index(fields=['-date'], name='live_replay_date_999d53_idx')],
            },
        ),
    ]
