# Generated by Django 5.1.4 on 2026-03-02 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='live_sessions.livereplaysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'session_attendances',
                'indexes': [models.Index(fields=['session'], name='session_att_session_8a0af7_idx'), models.Index(fields=['user'], name='session_att_user_id_e06046_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
    ]
